import '@/pages/blog/post/page/css/index.css'
import { Comments } from '@/pages/blog/post/page/components/Comments'

import exampleImg from '@/common/assets/images/default/banner.jpg';

export const Post = () => {
    return (
        <div className='flex flex-col items-center'>
            {/* blog content goes here */}
            <div className='p-2 text-pretty overflow-visible max-w-[900px] text-left'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit magna lacus, non fringilla est facilisis vitae. Nam semper ligula odio, id posuere lacus porttitor maximus. Nam tincidunt, libero non mattis tempor, ex diam cursus ex, in egestas erat nisl condimentum eros. Ut eget ante neque. Nunc vel nunc et lorem vulputate scelerisque ac malesuada augue. Donec a blandit quam, a mollis elit. In sodales pretium eros, eu molestie eros molestie vitae. Donec tortor arcu, tempor sed nisl sed, malesuada tempus sem. Donec sit amet diam porta arcu efficitur imperdiet. Ut at ornare ante, quis porttitor purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

                Nunc vitae velit quis nibh hendrerit tempus. Duis non nunc ultricies, feugiat sapien a, tempor leo. Mauris iaculis dolor lectus, sit amet aliquam tellus malesuada ut. Suspendisse faucibus porttitor turpis. Vestibulum id justo a arcu lacinia convallis quis pretium neque. Sed euismod quam id ex rhoncus, ullamcorper consectetur arcu condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis tellus tellus.

                Proin vitae maximus mi. Quisque laoreet molestie massa a posuere. Donec rutrum non nibh eget vestibulum. In hac habitasse platea dictumst. Aenean faucibus leo ante, vitae ultrices sapien iaculis non. In in mauris vitae ipsum dictum viverra ac eget risus. Ut nec elit suscipit, luctus massa quis, laoreet erat. Proin metus felis, convallis sit amet sagittis sed, condimentum vel leo.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In pretium ipsum quam, sed blandit enim pulvinar id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer eget ultricies ante. Nam suscipit egestas ornare. Ut vestibulum in nibh ut consequat. Fusce sed fermentum mi. Ut ac turpis pharetra, tincidunt sem nec, pulvinar justo. Suspendisse id hendrerit mauris. Nunc scelerisque massa et orci lacinia, vel vehicula ligula eleifend. Mauris pharetra est a enim dignissim tincidunt at non lectus.

                In suscipit nunc eu dolor facilisis suscipit. In pellentesque, augue et pretium blandit, lectus neque placerat mauris, nec ultricies diam dolor condimentum ante. Pellentesque in diam sed tellus lobortis elementum. Pellentesque sed enim eu erat lobortis malesuada. Aliquam vitae rhoncus justo. In mollis in nisi quis bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas lacinia orci in lacus faucibus, eu dictum leo hendrerit. Aliquam consectetur tristique odio et molestie. Donec fermentum rhoncus dolor, non dapibus sapien ullamcorper vitae. Praesent venenatis varius nisl ut gravida.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit magna lacus, non fringilla est facilisis vitae. Nam semper ligula odio, id posuere lacus porttitor maximus. Nam tincidunt, libero non mattis tempor, ex diam cursus ex, in egestas erat nisl condimentum eros. Ut eget ante neque. Nunc vel nunc et lorem vulputate scelerisque ac malesuada augue. Donec a blandit quam, a mollis elit. In sodales pretium eros, eu molestie eros molestie vitae. Donec tortor arcu, tempor sed nisl sed, malesuada tempus sem. Donec sit amet diam porta arcu efficitur imperdiet. Ut at ornare ante, quis porttitor purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

                Nunc vitae velit quis nibh hendrerit tempus. Duis non nunc ultricies, feugiat sapien a, tempor leo. Mauris iaculis dolor lectus, sit amet aliquam tellus malesuada ut. Suspendisse faucibus porttitor turpis. Vestibulum id justo a arcu lacinia convallis quis pretium neque. Sed euismod quam id ex rhoncus, ullamcorper consectetur arcu condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis tellus tellus.

                Proin vitae maximus mi. Quisque laoreet molestie massa a posuere. Donec rutrum non nibh eget vestibulum. In hac habitasse platea dictumst. Aenean faucibus leo ante, vitae ultrices sapien iaculis non. In in mauris vitae ipsum dictum viverra ac eget risus. Ut nec elit suscipit, luctus massa quis, laoreet erat. Proin metus felis, convallis sit amet sagittis sed, condimentum vel leo.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In pretium ipsum quam, sed blandit enim pulvinar id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer eget ultricies ante. Nam suscipit egestas ornare. Ut vestibulum in nibh ut consequat. Fusce sed fermentum mi. Ut ac turpis pharetra, tincidunt sem nec, pulvinar justo. Suspendisse id hendrerit mauris. Nunc scelerisque massa et orci lacinia, vel vehicula ligula eleifend. Mauris pharetra est a enim dignissim tincidunt at non lectus.

                In suscipit nunc eu dolor facilisis suscipit. In pellentesque, augue et pretium blandit, lectus neque placerat mauris, nec ultricies diam dolor condimentum ante. Pellentesque in diam sed tellus lobortis elementum. Pellentesque sed enim eu erat lobortis malesuada. Aliquam vitae rhoncus justo. In mollis in nisi quis bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas lacinia orci in lacus faucibus, eu dictum leo hendrerit. Aliquam consectetur tristique odio et molestie. Donec fermentum rhoncus dolor, non dapibus sapien ullamcorper vitae. Praesent venenatis varius nisl ut gravida.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit magna lacus, non fringilla est facilisis vitae. Nam semper ligula odio, id posuere lacus porttitor maximus. Nam tincidunt, libero non mattis tempor, ex diam cursus ex, in egestas erat nisl condimentum eros. Ut eget ante neque. Nunc vel nunc et lorem vulputate scelerisque ac malesuada augue. Donec a blandit quam, a mollis elit. In sodales pretium eros, eu molestie eros molestie vitae. Donec tortor arcu, tempor sed nisl sed, malesuada tempus sem. Donec sit amet diam porta arcu efficitur imperdiet. Ut at ornare ante, quis porttitor purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

                Nunc vitae velit quis nibh hendrerit tempus. Duis non nunc ultricies, feugiat sapien a, tempor leo. Mauris iaculis dolor lectus, sit amet aliquam tellus malesuada ut. Suspendisse faucibus porttitor turpis. Vestibulum id justo a arcu lacinia convallis quis pretium neque. Sed euismod quam id ex rhoncus, ullamcorper consectetur arcu condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis tellus tellus.

                Proin vitae maximus mi. Quisque laoreet molestie massa a posuere. Donec rutrum non nibh eget vestibulum. In hac habitasse platea dictumst. Aenean faucibus leo ante, vitae ultrices sapien iaculis non. In in mauris vitae ipsum dictum viverra ac eget risus. Ut nec elit suscipit, luctus massa quis, laoreet erat. Proin metus felis, convallis sit amet sagittis sed, condimentum vel leo.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In pretium ipsum quam, sed blandit enim pulvinar id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer eget ultricies ante. Nam suscipit egestas ornare. Ut vestibulum in nibh ut consequat. Fusce sed fermentum mi. Ut ac turpis pharetra, tincidunt sem nec, pulvinar justo. Suspendisse id hendrerit mauris. Nunc scelerisque massa et orci lacinia, vel vehicula ligula eleifend. Mauris pharetra est a enim dignissim tincidunt at non lectus.

                In suscipit nunc eu dolor facilisis suscipit. In pellentesque, augue et pretium blandit, lectus neque placerat mauris, nec ultricies diam dolor condimentum ante. Pellentesque in diam sed tellus lobortis elementum. Pellentesque sed enim eu erat lobortis malesuada. Aliquam vitae rhoncus justo. In mollis in nisi quis bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas lacinia orci in lacus faucibus, eu dictum leo hendrerit. Aliquam consectetur tristique odio et molestie. Donec fermentum rhoncus dolor, non dapibus sapien ullamcorper vitae. Praesent venenatis varius nisl ut gravida.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit magna lacus, non fringilla est facilisis vitae. Nam semper ligula odio, id posuere lacus porttitor maximus. Nam tincidunt, libero non mattis tempor, ex diam cursus ex, in egestas erat nisl condimentum eros. Ut eget ante neque. Nunc vel nunc et lorem vulputate scelerisque ac malesuada augue. Donec a blandit quam, a mollis elit. In sodales pretium eros, eu molestie eros molestie vitae. Donec tortor arcu, tempor sed nisl sed, malesuada tempus sem. Donec sit amet diam porta arcu efficitur imperdiet. Ut at ornare ante, quis porttitor purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

                Nunc vitae velit quis nibh hendrerit tempus. Duis non nunc ultricies, feugiat sapien a, tempor leo. Mauris iaculis dolor lectus, sit amet aliquam tellus malesuada ut. Suspendisse faucibus porttitor turpis. Vestibulum id justo a arcu lacinia convallis quis pretium neque. Sed euismod quam id ex rhoncus, ullamcorper consectetur arcu condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis tellus tellus.

                Proin vitae maximus mi. Quisque laoreet molestie massa a posuere. Donec rutrum non nibh eget vestibulum. In hac habitasse platea dictumst. Aenean faucibus leo ante, vitae ultrices sapien iaculis non. In in mauris vitae ipsum dictum viverra ac eget risus. Ut nec elit suscipit, luctus massa quis, laoreet erat. Proin metus felis, convallis sit amet sagittis sed, condimentum vel leo.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In pretium ipsum quam, sed blandit enim pulvinar id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer eget ultricies ante. Nam suscipit egestas ornare. Ut vestibulum in nibh ut consequat. Fusce sed fermentum mi. Ut ac turpis pharetra, tincidunt sem nec, pulvinar justo. Suspendisse id hendrerit mauris. Nunc scelerisque massa et orci lacinia, vel vehicula ligula eleifend. Mauris pharetra est a enim dignissim tincidunt at non lectus.

                In suscipit nunc eu dolor facilisis suscipit. In pellentesque, augue et pretium blandit, lectus neque placerat mauris, nec ultricies diam dolor condimentum ante. Pellentesque in diam sed tellus lobortis elementum. Pellentesque sed enim eu erat lobortis malesuada. Aliquam vitae rhoncus justo. In mollis in nisi quis bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas lacinia orci in lacus faucibus, eu dictum leo hendrerit. Aliquam consectetur tristique odio et molestie. Donec fermentum rhoncus dolor, non dapibus sapien ullamcorper vitae. Praesent venenatis varius nisl ut gravida.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit magna lacus, non fringilla est facilisis vitae. Nam semper ligula odio, id posuere lacus porttitor maximus. Nam tincidunt, libero non mattis tempor, ex diam cursus ex, in egestas erat nisl condimentum eros. Ut eget ante neque. Nunc vel nunc et lorem vulputate scelerisque ac malesuada augue. Donec a blandit quam, a mollis elit. In sodales pretium eros, eu molestie eros molestie vitae. Donec tortor arcu, tempor sed nisl sed, malesuada tempus sem. Donec sit amet diam porta arcu efficitur imperdiet. Ut at ornare ante, quis porttitor purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

                Nunc vitae velit quis nibh hendrerit tempus. Duis non nunc ultricies, feugiat sapien a, tempor leo. Mauris iaculis dolor lectus, sit amet aliquam tellus malesuada ut. Suspendisse faucibus porttitor turpis. Vestibulum id justo a arcu lacinia convallis quis pretium neque. Sed euismod quam id ex rhoncus, ullamcorper consectetur arcu condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis tellus tellus.

                Proin vitae maximus mi. Quisque laoreet molestie massa a posuere. Donec rutrum non nibh eget vestibulum. In hac habitasse platea dictumst. Aenean faucibus leo ante, vitae ultrices sapien iaculis non. In in mauris vitae ipsum dictum viverra ac eget risus. Ut nec elit suscipit, luctus massa quis, laoreet erat. Proin metus felis, convallis sit amet sagittis sed, condimentum vel leo.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In pretium ipsum quam, sed blandit enim pulvinar id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer eget ultricies ante. Nam suscipit egestas ornare. Ut vestibulum in nibh ut consequat. Fusce sed fermentum mi. Ut ac turpis pharetra, tincidunt sem nec, pulvinar justo. Suspendisse id hendrerit mauris. Nunc scelerisque massa et orci lacinia, vel vehicula ligula eleifend. Mauris pharetra est a enim dignissim tincidunt at non lectus.

                In suscipit nunc eu dolor facilisis suscipit. In pellentesque, augue et pretium blandit, lectus neque placerat mauris, nec ultricies diam dolor condimentum ante. Pellentesque in diam sed tellus lobortis elementum. Pellentesque sed enim eu erat lobortis malesuada. Aliquam vitae rhoncus justo. In mollis in nisi quis bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas lacinia orci in lacus faucibus, eu dictum leo hendrerit. Aliquam consectetur tristique odio et molestie. Donec fermentum rhoncus dolor, non dapibus sapien ullamcorper vitae. Praesent venenatis varius nisl ut gravida.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit magna lacus, non fringilla est facilisis vitae. Nam semper ligula odio, id posuere lacus porttitor maximus. Nam tincidunt, libero non mattis tempor, ex diam cursus ex, in egestas erat nisl condimentum eros. Ut eget ante neque. Nunc vel nunc et lorem vulputate scelerisque ac malesuada augue. Donec a blandit quam, a mollis elit. In sodales pretium eros, eu molestie eros molestie vitae. Donec tortor arcu, tempor sed nisl sed, malesuada tempus sem. Donec sit amet diam porta arcu efficitur imperdiet. Ut at ornare ante, quis porttitor purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

                Nunc vitae velit quis nibh hendrerit tempus. Duis non nunc ultricies, feugiat sapien a, tempor leo. Mauris iaculis dolor lectus, sit amet aliquam tellus malesuada ut. Suspendisse faucibus porttitor turpis. Vestibulum id justo a arcu lacinia convallis quis pretium neque. Sed euismod quam id ex rhoncus, ullamcorper consectetur arcu condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis tellus tellus.

                Proin vitae maximus mi. Quisque laoreet molestie massa a posuere. Donec rutrum non nibh eget vestibulum. In hac habitasse platea dictumst. Aenean faucibus leo ante, vitae ultrices sapien iaculis non. In in mauris vitae ipsum dictum viverra ac eget risus. Ut nec elit suscipit, luctus massa quis, laoreet erat. Proin metus felis, convallis sit amet sagittis sed, condimentum vel leo.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In pretium ipsum quam, sed blandit enim pulvinar id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer eget ultricies ante. Nam suscipit egestas ornare. Ut vestibulum in nibh ut consequat. Fusce sed fermentum mi. Ut ac turpis pharetra, tincidunt sem nec, pulvinar justo. Suspendisse id hendrerit mauris. Nunc scelerisque massa et orci lacinia, vel vehicula ligula eleifend. Mauris pharetra est a enim dignissim tincidunt at non lectus.

                In suscipit nunc eu dolor facilisis suscipit. In pellentesque, augue et pretium blandit, lectus neque placerat mauris, nec ultricies diam dolor condimentum ante. Pellentesque in diam sed tellus lobortis elementum. Pellentesque sed enim eu erat lobortis malesuada. Aliquam vitae rhoncus justo. In mollis in nisi quis bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas lacinia orci in lacus faucibus, eu dictum leo hendrerit. Aliquam consectetur tristique odio et molestie. Donec fermentum rhoncus dolor, non dapibus sapien ullamcorper vitae. Praesent venenatis varius nisl ut gravida.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit magna lacus, non fringilla est facilisis vitae. Nam semper ligula odio, id posuere lacus porttitor maximus. Nam tincidunt, libero non mattis tempor, ex diam cursus ex, in egestas erat nisl condimentum eros. Ut eget ante neque. Nunc vel nunc et lorem vulputate scelerisque ac malesuada augue. Donec a blandit quam, a mollis elit. In sodales pretium eros, eu molestie eros molestie vitae. Donec tortor arcu, tempor sed nisl sed, malesuada tempus sem. Donec sit amet diam porta arcu efficitur imperdiet. Ut at ornare ante, quis porttitor purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

                Nunc vitae velit quis nibh hendrerit tempus. Duis non nunc ultricies, feugiat sapien a, tempor leo. Mauris iaculis dolor lectus, sit amet aliquam tellus malesuada ut. Suspendisse faucibus porttitor turpis. Vestibulum id justo a arcu lacinia convallis quis pretium neque. Sed euismod quam id ex rhoncus, ullamcorper consectetur arcu condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis tellus tellus.

                Proin vitae maximus mi. Quisque laoreet molestie massa a posuere. Donec rutrum non nibh eget vestibulum. In hac habitasse platea dictumst. Aenean faucibus leo ante, vitae ultrices sapien iaculis non. In in mauris vitae ipsum dictum viverra ac eget risus. Ut nec elit suscipit, luctus massa quis, laoreet erat. Proin metus felis, convallis sit amet sagittis sed, condimentum vel leo.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In pretium ipsum quam, sed blandit enim pulvinar id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer eget ultricies ante. Nam suscipit egestas ornare. Ut vestibulum in nibh ut consequat. Fusce sed fermentum mi. Ut ac turpis pharetra, tincidunt sem nec, pulvinar justo. Suspendisse id hendrerit mauris. Nunc scelerisque massa et orci lacinia, vel vehicula ligula eleifend. Mauris pharetra est a enim dignissim tincidunt at non lectus.

                In suscipit nunc eu dolor facilisis suscipit. In pellentesque, augue et pretium blandit, lectus neque placerat mauris, nec ultricies diam dolor condimentum ante. Pellentesque in diam sed tellus lobortis elementum. Pellentesque sed enim eu erat lobortis malesuada. Aliquam vitae rhoncus justo. In mollis in nisi quis bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas lacinia orci in lacus faucibus, eu dictum leo hendrerit. Aliquam consectetur tristique odio et molestie. Donec fermentum rhoncus dolor, non dapibus sapien ullamcorper vitae. Praesent venenatis varius nisl ut gravida.
                <img src={exampleImg}
                />
            </div>
            <Comments className=''/>
        </div>

    )
}
