# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches: [ "publish-fe", "publish-be" ]
    paths: ['.github/workflows/**', 'Projects/**']
  workflow_dispatch:

jobs:
  stop-docker:
    if: | 
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted]
    steps:
      - name: Stop docker
        run: sudo docker rm -f jeheecheon-blog-be-container

  build-and-deploy-fe:
    needs: stop-docker
    if: |
      github.event_name == 'push' && (github.ref == 'refs/heads/publish-fe') ||
      github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ./Projects/fe
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: Projects/fe/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - name: Run docker container
        run: sudo systemctl restart docker-container-start.service


  build-be:
    needs: stop-docker
    if: | 
      github.event_name == 'push' && (github.ref == 'refs/heads/publish-be') || 
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Projects/be
    steps:
      - name: Checkout sourse
        uses: actions/checkout@v3
      - name: Use .NET SDK version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.101'
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t jeheecheon/jeheecheon-blog-be .
      - name: Publish image to docker hub
        run: docker push jeheecheon/jeheecheon-blog-be:latest


  deploy-be:
    if: | 
      github.event_name == 'push' && (github.ref == 'refs/heads/publish-be') || 
      github.event_name == 'workflow_dispatch'
    needs: build-be
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ./Projects/be
    steps:
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: sudo docker pull jeheecheon/jeheecheon-blog-be:latest
      - name: Delete old container
        run: sudo docker rm -f jeheecheon-blog-be-container
      - name: Run docker container
        run: sudo systemctl restart docker-container-start.service